version: '3'

networks:
  hugo_network_book_ansible:
    driver: bridge


services:

  ## for testing static file from hugo build
  nginx:
    image: nginx:${DK_NGINX_VER:-stable-alpine}
    container_name: ${DK_NGINX_NAME:-nginx_ansible}
    restart: unless-stopped
    volumes:
      - ${DIST_DIR:-./src/dist}:/usr/share/nginx/html:ro
    networks:
      - hugo_network_book_ansible
    ports:
      - ${NGINX_PORT:-9998}:80

  # hugo service to run hugo commands
  hugo:
    image: klakegg/hugo:${DK_HUGO_VER:-ext-alpine}
    container_name: ${DK_HUGO_NAME:-hugo_ansible}
    user: ${CURRENT_USER:-1000:1000}
    command: help
    volumes:
      - ${SRC_DIR:-./src}:/src

  # hugo server
  server:
    image: klakegg/hugo:${DK_HUGO_VER:-ext-alpine}
    container_name: ${DK_HUGO_SERVER_NAME:-hugo_ansible_server}
    user: ${CURRENT_USER:-1000:1000}
    restart: unless-stopped
    command: ["server", "--watch", "--port", "${HUGO_PORT:-1313}", "--liveReloadPort", "${HUGO_PORT:-1313}", "-D"]
    volumes:
      - ${SRC_DIR:-./src}:/src
    networks: 
      - hugo_network_book_ansible
    ports:
      - ${HUGO_PORT:-1313}:${HUGO_PORT:-1313}
